<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <!--
    二、async-await实现多个异步耗时操作有顺序
    既然存在”回调地狱“的困境，那把回调干掉不就完事了嘛，这就是async-await做的事情，async-await确实没回调了！
  -->
  <!--
    1、半async-await实现多个异步耗时操作有顺序和Promise实现多个异步耗时操作有顺序不同的地方
    这里的”半async-await“是指异步耗时操作函数定义阶段还是使用Promise，仅在异步耗时操作函数调用阶段使用async-await，我们一步一步来得出最终的结论
    ——————————————————————
    * 异步耗时操作函数定义阶段：
      * 完全不需要变，可以保持跟使用Promise时一模一样
    ——————————————————————
    * 异步耗时操作函数调用阶段：
      * 原来我们是通过Promise对象.then的第一个函数来监听成功的数据
      * 现在是用await来监听成功的数据；当然await除了具备监听成功的数据这一大功能外，await的第二大功能就是它会卡在这里一直等、直到等到了成功的数据才会放行，这也是为什么await能实现多个异步耗时操作按顺序串行执行的原因
      
      * 原来我们是通过Promise对象.then的第二个函数来监听失败的错误
      * 现在用try-catch的catch来监听失败的错误（也就是说我们一旦使用了async-await这一套，就一定要为await随身绑定一套try-catch，否则异步耗时操作执行失败的错误没人处理的话代码也会崩溃。这也是为什么我们在使用很多三方库的时候，发现人家的一些异步任务超时后或者访问不到后都是直接给外界throw Error，我们不用try-catch处理的话代码就会崩溃的原因）
    ——————————————————————
    综上，也就是说Promise对象的executor函数里一旦调用了resolve（即成功上报函数）函数、就一定会触发await，executor函数里一旦调用了reject（即失败上报函数）函数、就一定会触发try-catch的catch
  -->
  <script>
    // getInterface1还是原来的同步函数 + Promise
    function getInterface1() {
      const promise = new Promise((resolve, reject) => {
        fetch("https://www.bing.com", {
          mode: 'no-cors', // 设置为 no-cors
        }).then(
          (value) => {
            resolve(value);
          },
          (error) => {
            reject(error);
          },
        );
      });

      return promise;
    }

    // getInterface2还是原来的同步函数 + Promise
    function getInterface2() {
      const promise = new Promise((resolve, reject) => {
        fetch("https://www.baidu.com", {
          mode: 'no-cors', // 设置为 no-cors
        }).then(
          (value) => {
            resolve(value);
          },
          (error) => {
            reject(error);
          },
        );
      });

      return promise;
    }

    async function getAllInterface() {
      try {
        // 卡在这里等接口1成功的数据，然后再放行去获取接口2
        const value1 = await getInterface1();
        console.log(`接口1请求成功：${value1}`);

        // 卡在这里等接口2成功的数据
        const value2 = await getInterface2();
        console.log(`接口2请求成功：${value2}`);
      } catch (error) {
        console.log(`接口1请求失败 | 接口2请求成功失败：${error}`);
      }
    };
    // getAllInterface();
  </script>

  <!--
    2、全async-await实现多个异步耗时操作有顺序和Promise实现多个异步耗时操作有顺序不同的地方
    实际上async-await除了在调用异步耗时操作函数阶段和Promise有不同之外————即解决回调地狱问题以外（这是我们使用async-await第一大原因），在定义异步耗时操作阶段也可以有不同————即async-await的代码本身就可以比Promise更加简洁清晰（当没有回调地狱时，我们依然可以使用async-await，这就是我们使用async-await第二大原因），所以这里的“全async-await”是在定义和调用异步耗时操作阶段都是用async-await
    ——————————————————————
    * 异步耗时操作函数定义阶段：
      * （0）上来二话不说，先用async关键字修饰一下异步耗时操作函数
      * （1）异步耗时操作函数的【参数】：不需要变，保持没有回调函数这样的参数
      * （2）异步耗时操作函数的【返回值】：不需要变，保持返回一个Promise对象、以便外界监听异步耗时操作的结果（不过这里不再需要我们显式地返回一个Promise对象，async函数会帮我们自动返回一个Promise对象）
      * （3）异步耗时操作函数的【执行体】：需要变、且变得非常彻底、每一步都变了
        * ① 【创建Promise对象和返回Promise对象的变化】：原来我们是显性地手动创建了一个Promise对象、并返回了这个Promise对象，现在不需要了，async函数内部会隐式地自动创建一个Promise对象、我们只需要返回普通数据类型的值即可、async函数内部会自动把普通数据类型的值包装进Promise对象并返回Promise对象
        * ② 【耗时耗时操作放在哪里执行的变化】：原来我们是把耗时操作放在Promise对象的executor函数里执行的，现在不是了，而是要放在try-catch里执行，因为我们需要通过await来等待异步耗时操作成功的数据和用catch来捕获异步耗时操作失败的错误
        * ③ 【上报成功数据和失败错误方式的变化】：原来我们是通过Promise对象的executor函数的resolve上报耗时操作执行成功的数据、reject上报耗时操作执行失败的错误，现在不是了，现在是通过异步耗时操作函数的返回值上报成功的数据————代替resolve，通过在异步任务函数执行体里抛出异常来上报失败的信息————代替reject（此时回想一下我们在使用很多三方库的时候，人家的一些异步任务超时后或者访问不到后都是直接给外界throw Error，这就是一个标准做法，我们以后在设计async函数时也要这样设计）
    ——————————————————————
    * 异步耗时操作函数调用阶段：
      * 原来我们是通过Promise对象.then的第一个函数来监听成功的数据
      * 现在是用await来监听成功的数据；当然await除了具备监听成功的数据这一大功能外，await的第二大功能就是它会卡在这里一直等、直到等到了成功的数据才会放行，这也是为什么await能实现多个异步耗时操作按顺序串行执行的原因
      
      * 原来我们是通过Promise对象.then的第二个函数来监听失败的错误
      * 现在用try-catch的catch来监听失败的错误（也就是说我们一旦使用了async-await这一套，就一定要为await随身绑定一套try-catch，否则异步耗时操作执行失败的错误没人处理的话代码也会崩溃。这也是为什么我们在使用很多三方库的时候，发现人家的一些异步任务超时后或者访问不到后都是直接给外界throw Error，我们不用try-catch处理的话代码就会崩溃的原因）
  -->
  <script>
    // getInterface1Async不再是一个同步函数了，而是一个异步函数，把它搞成异步函数有两个好处：
    // 1、它内部的异步耗时操作就可以不用Promise来写了，而是可以用await来写（因为await只能用在async函数里），这样代码可以更加简洁清晰
    // 2、外界在调用这个异步耗时操作函数时，也不会阻塞主线程（毕竟是个耗时操作嘛），而是可以继续执行其它操作，效率更高，当然我们要自己注意好操作的同步问题
    async function getInterface1Async() {
      try {
        // 卡在这里等待接口成功的数据
        const value = await fetch("https://www.bing.com", {
          mode: 'no-cors', // 设置为 no-cors
        });
        // 这就是在上报成功的数据（会自动包装进一个Promise对象返回）
        return value;
      } catch (error) {
        // 捕获接口失败的错误，并用throw Error上报失败的错误
        throw Error(error);
      }
    }

    // getInterface2Async不再是一个同步函数了，而是一个异步函数
    async function getInterface2Async() {
      try {
        // 卡在这里等待接口成功的数据
        const value = await fetch("https://www.baidu.com", {
          mode: 'no-cors', // 设置为 no-cors
        });
        // 这就是在上报成功的数据（会自动包装进一个Promise对象返回）
        return value;
      } catch (error) {
        // 捕获接口失败的错误，并用throw Error上报失败的错误
        throw Error(error);
      }
    }

    async function getAllInterfaceAgain() {
      try {
        // 卡在这里等接口1成功的数据，然后再放行去获取接口2
        const value1 = await getInterface1Async();
        console.log(`接口1请求成功：${value1}`);

        // 卡在这里等接口2成功的数据
        const value2 = await getInterface2Async();
        console.log(`接口2请求成功：${value2}`);
      } catch (error) {
        console.log(`接口1请求失败 | 接口2请求成功失败：${error}`);
      }
    };
    getAllInterfaceAgain();
  </script>

  <!--
    3、半async-await和全async-await的写法就是上面那样的固定写法，一定要牢记于心，实际开发中半async-await和全async-await都有可能会用到

    全async-await只能用在异步耗时操作本身就返回一个Promise的情况（如网络请求、本地IO操作），因为await后面只能跟一个Promise
    半async-await则既能用在异步耗时操作本身就返回一个Promise的情况（如网络请求、本地IO操作），也能用在异步耗时操作本身不返回一个Promise的情况（如蓝牙通信、setTimeout）
  -->
</body>

</html>